AWSTemplateFormatVersion: "2010-09-09"

Description: Simple S3 bucket created using GitHub Actions and CloudFormation

Resources:

  DemoBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Environment
          Value: Demo
        - Key: ManagedBy
          Value: CloudFormation

Outputs:

  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref DemoBucket